use crate::analyzer;
use crate::templates;
use std::env;
use std::fs;

/// Generate .gitignore file based on detected or specified technologies
pub fn generate(force: bool, custom: &[String]) -> Result<(), String> {
    let path = env::current_dir().map_err(|e| format!("Failed to get current directory: {}", e))?;

    // Check if .gitignore exists
    let gitignore_path = path.join(".gitignore");
    if gitignore_path.exists() && !force {
        return Err("A .gitignore file already exists. Use --force to overwrite.".to_string());
    }

    // Get technologies: custom if provided, otherwise auto-detect
    let technologies = if custom.is_empty() {
        let detected = analyzer::analyze_project(&path);
        if detected.is_empty() {
            return Err(
                "No supported technologies detected. Try specifying manually: gitignore-gen rust"
                    .to_string(),
            );
        }
        detected
    } else {
        // Validate custom templates exist
        let mut valid = Vec::new();
        for tech in custom {
            if templates::get_template(tech).is_some() {
                valid.push(tech.clone());
            } else {
                eprintln!("Warning: Unknown template '{}', skipping", tech);
            }
        }
        if valid.is_empty() {
            return Err(
                "No valid templates specified. Use --list to see available templates.".to_string()
            );
        }
        valid
    };

    // Build combined gitignore content
    let content = build_gitignore(&technologies)?;

    // Write file
    fs::write(&gitignore_path, &content)
        .map_err(|e| format!("Failed to write .gitignore file: {}", e))?;

    println!("Generated .gitignore for: {}", technologies.join(", "));
    Ok(())
}

/// Build combined .gitignore content from technologies
fn build_gitignore(technologies: &[String]) -> Result<String, String> {
    let mut content = String::new();
    content.push_str("# Generated by gitignore-gen\n");
    content.push_str(&format!("# Technologies: {}\n\n", technologies.join(", ")));

    for tech in technologies {
        if let Some(template) = templates::get_template(tech) {
            content.push_str(&format!("### {} ###\n", tech));
            content.push_str(template);
            content.push_str("\n\n");
        }
    }

    if content.lines().count() <= 3 {
        return Err("No templates found for specified technologies".to_string());
    }

    Ok(content)
}
